# Generated by Django 5.0.7 on 2024-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('detailed_content', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'ap_news',
                'managed': True,
            },
        ),
    ]
