# Generated by Django 5.0.7 on 2024-08-05 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('priority_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('other_category', models.ForeignKey(db_column='category_id1', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='news_app.category')),
            ],
            options={
                'db_table': 'sub_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductionApNewsModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('category_id', models.ForeignKey(max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='news_app.category')),
                ('news_sub_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_sub_category_id', to='news_app.newssubcategory')),
            ],
            options={
                'db_table': 'production_ap_news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StagingApNewsModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid4, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.newssubcategory')),
            ],
            options={
                'db_table': 'ap_news',
                'managed': True,
            },
        ),
    ]
